from .variety_product_exceptions import VarietyIdNotFoundException, VarietyNotFoundException, \
    VarietyOutOfStockException, NoNewVarietiesException, VarietyAlreadyInDatabaseException, NoDiscountVarietiesException
